name: Greetings
on: workflow_dispatch
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet'
        run: 
          echo "Hello✌️"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Test'
        run: 
          echo "Testing the app✌️"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'deploy'
        run: 
          echo "Deploying the app✌️"
        
    
