name: ABC

on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: |
          echo "Hello {{vars.Name}}✌️"

  test:
    runs-on: ubuntu-latest
    needs: greet
    steps:
      - name: Test
        run: |
          echo "Testing the app✌️"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy
        run: |
          echo "Deploying the app✌️"
